name: flutter_application_coba_capsten
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  http: ^1.2.2
  image_picker: ^0.8.7+3
  get: ^4.6.6
  shared_preferences: ^2.0.16
  dropdown_button2: ^2.0.0
  geolocator: ^10.0.1
  google_maps_flutter: ^2.2.1  # Update to the latest version if needed
  location: ^5.0.0 
  geocoding: ^2.0.5
  firebase_core: ^2.12.0
  firebase_auth: ^4.7.0
  google_sign_in: ^6.0.0
  permission_handler: ^10.2.0
  


dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/background.jpg

  fonts:
    - family: Lemon
      fonts:
        - asset: assets/fonts/LEMON.ttf
